{% set name = "bw2io" %}
{% set version = "0.5.8.1" %}
{% set sha256 = "232b4c5b0ca342ab86060d941ecfbbd8949c2c97fb1b0c7bd9a880f7cde6fea6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bw2io = bw2io:main
    #
    # Would create an entry point called bw2io that calls bw2io.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bw2calc >=1.4
    - lxml
    - numpy
    - psutil
    - pyprind
    - scipy
    - stats_arrays
    - unidecode
    - voluptuous
    - xlsxwriter
    - xlrd
    - appdirs
    - bw2parameters
    - docopt
    - eight
    - fasteners
    - future
    - lxml
    - peewee >=2.7.4
    - requests >=1.1.0
    - scipy
    - stats_arrays
    - unicodecsv
    - whoosh
    - wrapt

  run:
    - python
    - bw2calc >=1.4
    - lxml
    - numpy
    - psutil
    - pyprind
    - scipy
    - stats_arrays
    - unidecode
    - voluptuous
    - xlsxwriter
    - xlrd
    - appdirs
    - bw2parameters
    - docopt
    - eight
    - fasteners
    - future
    - lxml
    - peewee >=2.7.4
    - requests >=1.1.0
    - scipy
    - stats_arrays
    - unicodecsv
    - whoosh
    - wrapt

test:
  # Python imports
  imports:
    - bw2io
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/cmutel/brightway2-io
  license: BSD License
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
