{% set name = "brightway2" %}
{% set version = "2.1" %}
{% set sha256 = "2c2b3ba236bce5c17a7cf8239455c865721b31b6f0fc521792177bb5a789d628" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - brightway2 = brightway2:main
    #
    # Would create an entry point called brightway2 that calls brightway2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - appdirs
    - asteval
    - bw2analyzer
    - bw2calc
    - bw2data
    - bw2io
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - lxml
    - nose
    - numpy
    - peewee >=2.8
    - psutil
    - pyprind
    - requests
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter
    - pypardiso

  run:
    - python
    - appdirs
    - asteval
    - bw2analyzer
    - bw2calc
    - bw2data
    - bw2io
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - lxml
    - nose
    - numpy
    - peewee >=2.8
    - psutil
    - pyprind
    - requests
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter
    - pypardiso

test:
  # Python imports
  imports:
    - brightway2

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/cmutel/brightway2
  license: BSD License
  summary: 'UNKNOWN'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
